version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    ignore:
      # importlib-resources, a non-critical dependency, version 6.+ does not support Python 3.7
      - dependency-name: "importlib-resources"
        versions: ["6.x"]
    groups:
      grpc-deps:
        patterns:
          - "grpcio*"
  - package-ecosystem: gradle
    directory: /java/
    schedule:
      interval: daily
    groups:
      grpc-deps:
        patterns:
          - "io.grpc*"
  - package-ecosystem: gomod
    directory: /go/
    schedule:
      interval: daily
    groups:
      grpc-deps:
        patterns:
          - "google.golang.org/grpc*"
