version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    groups:
      grpc-deps:
        patterns:
          - "grpcio*"
  - package-ecosystem: gradle
    directory: /java/
    schedule:
      interval: daily
    ignore:
      # grpc-java does not support 4.x of protobuf
      - dependency-name: "com.google.protobuf:proto*"
        versions: ["4.x"]
    groups:
      grpc-deps:
        patterns:
          - "io.grpc*"
  - package-ecosystem: gomod
    directory: /go/
    schedule:
      interval: daily
    groups:
      grpc-deps:
        patterns:
          - "google.golang.org/grpc*"
