version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    versioning-strategy: "widen"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/java/"
    schedule:
      interval: "weekly"
