# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
    os: ubuntu-22.04
    tools:
        python: "3.10"
    jobs:
        pre_install:
            - git update-index --assume-unchanged python/docs/conf.py

sphinx:
    configuration: python/docs/conf.py

python:
    install:
        - method: pip
          path: .[docs]
