FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update

RUN apt-get -qy install git
RUN apt-get -qy install openjdk-11-jdk-headless
RUN apt-get -qy install build-essential
RUN apt-get -qy install python3 python3-pip

WORKDIR /home/mtap

RUN pip3 install --upgrade pip
RUN python3 -m pip install --upgrade setuptools

COPY . mtap

RUN pip3 install ./mtap
RUN ./mtap/java/gradlew -p /home/mtap/mtap/java clean build shadowJar publishToMavenLocal

ENTRYPOINT /bin/sh
