FROM ubuntu:latest

ENV PYTHONBUFFERED TRUE

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    python3-dev \
    python3-pip \
    build-essential \
    openjdk-8-jdk-headless \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1
RUN update-alternatives --install /usr/local/bin/pip pip /usr/bin/pip3 1

RUN python -m pip install --upgrade pip

COPY . /mtap/

RUN pip install --no-cache-dir /mtap

ENV JAVA_OPTS="-Xmx512m \"-XX:MaxMetaspaceSize=256m\""
RUN /mtap/java/gradlew --no-build-cache --no-daemon --stacktrace -p /mtap/java publishToMavenLocal

ENTRYPOINT ["bin", "bash"]
