discovery: consul
consul:
  host: localhost
  port: 8500
  scheme: http
  # Python uses {python_naming_scheme}:address[:port][,address[:port],...] as grpc targets
  python_naming_scheme: ipv4

gateway:
  port: 8080
  refresh_interval: 10
  events: null  # localhost:9090
  processors: []
#    - Identifier: nlpnewt-example-processor-python
#      Endpoint: localhost:9091
