// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mtap/api/v1/processing.proto

package mtap_api_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	_struct "github.com/golang/protobuf/ptypes/struct"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The name of a newly created label index during a process call.
type CreatedIndex struct {
	// The document's name where the index was created.
	DocumentName string `protobuf:"bytes,1,opt,name=document_name,json=documentName,proto3" json:"document_name,omitempty"`
	// The name of the label index that was created.
	IndexName            string   `protobuf:"bytes,2,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatedIndex) Reset()         { *m = CreatedIndex{} }
func (m *CreatedIndex) String() string { return proto.CompactTextString(m) }
func (*CreatedIndex) ProtoMessage()    {}
func (*CreatedIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_92219fa19b46411c, []int{0}
}

func (m *CreatedIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatedIndex.Unmarshal(m, b)
}
func (m *CreatedIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatedIndex.Marshal(b, m, deterministic)
}
func (m *CreatedIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatedIndex.Merge(m, src)
}
func (m *CreatedIndex) XXX_Size() int {
	return xxx_messageInfo_CreatedIndex.Size(m)
}
func (m *CreatedIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatedIndex.DiscardUnknown(m)
}

var xxx_messageInfo_CreatedIndex proto.InternalMessageInfo

func (m *CreatedIndex) GetDocumentName() string {
	if m != nil {
		return m.DocumentName
	}
	return ""
}

func (m *CreatedIndex) GetIndexName() string {
	if m != nil {
		return m.IndexName
	}
	return ""
}

// A request for a processor to run on a specific event.
type ProcessRequest struct {
	// The identifier of the processor that is being called, currently is unused
	// but may be eventually used for routing if multiple processors are hosted
	// on the same port / endpoint.
	ProcessorId string `protobuf:"bytes,1,opt,name=processor_id,json=processorId,proto3" json:"processor_id,omitempty"`
	// The identifier of the event to process.
	EventId string `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// A dynamic JSON object of runtime parameters that the processor will use.
	Params               *_struct.Struct `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ProcessRequest) Reset()         { *m = ProcessRequest{} }
func (m *ProcessRequest) String() string { return proto.CompactTextString(m) }
func (*ProcessRequest) ProtoMessage()    {}
func (*ProcessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92219fa19b46411c, []int{1}
}

func (m *ProcessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessRequest.Unmarshal(m, b)
}
func (m *ProcessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessRequest.Marshal(b, m, deterministic)
}
func (m *ProcessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessRequest.Merge(m, src)
}
func (m *ProcessRequest) XXX_Size() int {
	return xxx_messageInfo_ProcessRequest.Size(m)
}
func (m *ProcessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessRequest proto.InternalMessageInfo

func (m *ProcessRequest) GetProcessorId() string {
	if m != nil {
		return m.ProcessorId
	}
	return ""
}

func (m *ProcessRequest) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *ProcessRequest) GetParams() *_struct.Struct {
	if m != nil {
		return m.Params
	}
	return nil
}

// The response after a processor completes processing of an event.
type ProcessResponse struct {
	// Processor-specific timings of different operations. Includes a "process"
	// time for total time taken.
	TimingInfo map[string]*duration.Duration `protobuf:"bytes,1,rep,name=timing_info,json=timingInfo,proto3" json:"timing_info,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// The dynamic JSON object result returned by the processor.
	Result *_struct.Struct `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	// All label indices that were created on the event during processing.
	CreatedIndices       []*CreatedIndex `protobuf:"bytes,3,rep,name=created_indices,json=createdIndices,proto3" json:"created_indices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ProcessResponse) Reset()         { *m = ProcessResponse{} }
func (m *ProcessResponse) String() string { return proto.CompactTextString(m) }
func (*ProcessResponse) ProtoMessage()    {}
func (*ProcessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92219fa19b46411c, []int{2}
}

func (m *ProcessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessResponse.Unmarshal(m, b)
}
func (m *ProcessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessResponse.Marshal(b, m, deterministic)
}
func (m *ProcessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessResponse.Merge(m, src)
}
func (m *ProcessResponse) XXX_Size() int {
	return xxx_messageInfo_ProcessResponse.Size(m)
}
func (m *ProcessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessResponse proto.InternalMessageInfo

func (m *ProcessResponse) GetTimingInfo() map[string]*duration.Duration {
	if m != nil {
		return m.TimingInfo
	}
	return nil
}

func (m *ProcessResponse) GetResult() *_struct.Struct {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ProcessResponse) GetCreatedIndices() []*CreatedIndex {
	if m != nil {
		return m.CreatedIndices
	}
	return nil
}

// Request for processor information.
type GetInfoRequest struct {
	// The identifier of the processor, currently is unused but may be eventually used for routing
	// if multiple processors are hosted on the same port / endpoint.
	ProcessorId          string   `protobuf:"bytes,1,opt,name=processor_id,json=processorId,proto3" json:"processor_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoRequest) Reset()         { *m = GetInfoRequest{} }
func (m *GetInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetInfoRequest) ProtoMessage()    {}
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92219fa19b46411c, []int{3}
}

func (m *GetInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoRequest.Unmarshal(m, b)
}
func (m *GetInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoRequest.Merge(m, src)
}
func (m *GetInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetInfoRequest.Size(m)
}
func (m *GetInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoRequest proto.InternalMessageInfo

func (m *GetInfoRequest) GetProcessorId() string {
	if m != nil {
		return m.ProcessorId
	}
	return ""
}

// Processor information response, currently does not include anything besides
// the processor name. May eventually be extended to reflect more processor
// information like documentation, required inputs (label indices and
// parameters), and outputs (label indices and parameters), etc.
type GetInfoResponse struct {
	// The name of the processor.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The deployment identifier for the processor.
	Identifier string `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// A short description of what the processor does.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// The processor's entry point / main class.
	EntryPoint string `protobuf:"bytes,4,opt,name=entry_point,json=entryPoint,proto3" json:"entry_point,omitempty"`
	// The processor coding language.
	Language string `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	// Descriptions of the processor's parameters.
	Parameters []*GetInfoResponse_ParameterDescription `protobuf:"bytes,6,rep,name=parameters,proto3" json:"parameters,omitempty"`
	// Descriptions of the input label indices.
	Inputs []*GetInfoResponse_LabelIndexDescription `protobuf:"bytes,7,rep,name=inputs,proto3" json:"inputs,omitempty"`
	// Descriptions of the output label indices.
	Outputs              []*GetInfoResponse_LabelIndexDescription `protobuf:"bytes,8,rep,name=outputs,proto3" json:"outputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *GetInfoResponse) Reset()         { *m = GetInfoResponse{} }
func (m *GetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetInfoResponse) ProtoMessage()    {}
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92219fa19b46411c, []int{4}
}

func (m *GetInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoResponse.Unmarshal(m, b)
}
func (m *GetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoResponse.Merge(m, src)
}
func (m *GetInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetInfoResponse.Size(m)
}
func (m *GetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoResponse proto.InternalMessageInfo

func (m *GetInfoResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetInfoResponse) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *GetInfoResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetInfoResponse) GetEntryPoint() string {
	if m != nil {
		return m.EntryPoint
	}
	return ""
}

func (m *GetInfoResponse) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *GetInfoResponse) GetParameters() []*GetInfoResponse_ParameterDescription {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *GetInfoResponse) GetInputs() []*GetInfoResponse_LabelIndexDescription {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *GetInfoResponse) GetOutputs() []*GetInfoResponse_LabelIndexDescription {
	if m != nil {
		return m.Outputs
	}
	return nil
}

// A description of processor parameters.
type GetInfoResponse_ParameterDescription struct {
	// The parameter name / key.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A short description of the parameter and what it does.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// The expected data type of the parameter.
	DataType string `protobuf:"bytes,3,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	// Whether the parameter is required, i.e. needed by the processor in order to function.
	Required             bool     `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoResponse_ParameterDescription) Reset()         { *m = GetInfoResponse_ParameterDescription{} }
func (m *GetInfoResponse_ParameterDescription) String() string { return proto.CompactTextString(m) }
func (*GetInfoResponse_ParameterDescription) ProtoMessage()    {}
func (*GetInfoResponse_ParameterDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_92219fa19b46411c, []int{4, 0}
}

func (m *GetInfoResponse_ParameterDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoResponse_ParameterDescription.Unmarshal(m, b)
}
func (m *GetInfoResponse_ParameterDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoResponse_ParameterDescription.Marshal(b, m, deterministic)
}
func (m *GetInfoResponse_ParameterDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoResponse_ParameterDescription.Merge(m, src)
}
func (m *GetInfoResponse_ParameterDescription) XXX_Size() int {
	return xxx_messageInfo_GetInfoResponse_ParameterDescription.Size(m)
}
func (m *GetInfoResponse_ParameterDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoResponse_ParameterDescription.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoResponse_ParameterDescription proto.InternalMessageInfo

func (m *GetInfoResponse_ParameterDescription) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetInfoResponse_ParameterDescription) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetInfoResponse_ParameterDescription) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

func (m *GetInfoResponse_ParameterDescription) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

// A description of the input and output label indices of a processor.
type GetInfoResponse_LabelIndexDescription struct {
	// The default name of the label index.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// If the name comes from a parameter, the key for that parameter.
	NameFromParameter string `protobuf:"bytes,2,opt,name=name_from_parameter,json=nameFromParameter,proto3" json:"name_from_parameter,omitempty"`
	// Whether the label index is an optional input.
	Optional bool `protobuf:"varint,3,opt,name=optional,proto3" json:"optional,omitempty"`
	// A description of the label index.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// The properties of the labels.
	Properties           []*GetInfoResponse_LabelIndexDescription_PropertyDescription `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                     `json:"-"`
	XXX_unrecognized     []byte                                                       `json:"-"`
	XXX_sizecache        int32                                                        `json:"-"`
}

func (m *GetInfoResponse_LabelIndexDescription) Reset()         { *m = GetInfoResponse_LabelIndexDescription{} }
func (m *GetInfoResponse_LabelIndexDescription) String() string { return proto.CompactTextString(m) }
func (*GetInfoResponse_LabelIndexDescription) ProtoMessage()    {}
func (*GetInfoResponse_LabelIndexDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_92219fa19b46411c, []int{4, 1}
}

func (m *GetInfoResponse_LabelIndexDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoResponse_LabelIndexDescription.Unmarshal(m, b)
}
func (m *GetInfoResponse_LabelIndexDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoResponse_LabelIndexDescription.Marshal(b, m, deterministic)
}
func (m *GetInfoResponse_LabelIndexDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoResponse_LabelIndexDescription.Merge(m, src)
}
func (m *GetInfoResponse_LabelIndexDescription) XXX_Size() int {
	return xxx_messageInfo_GetInfoResponse_LabelIndexDescription.Size(m)
}
func (m *GetInfoResponse_LabelIndexDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoResponse_LabelIndexDescription.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoResponse_LabelIndexDescription proto.InternalMessageInfo

func (m *GetInfoResponse_LabelIndexDescription) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetInfoResponse_LabelIndexDescription) GetNameFromParameter() string {
	if m != nil {
		return m.NameFromParameter
	}
	return ""
}

func (m *GetInfoResponse_LabelIndexDescription) GetOptional() bool {
	if m != nil {
		return m.Optional
	}
	return false
}

func (m *GetInfoResponse_LabelIndexDescription) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetInfoResponse_LabelIndexDescription) GetProperties() []*GetInfoResponse_LabelIndexDescription_PropertyDescription {
	if m != nil {
		return m.Properties
	}
	return nil
}

// A description of the properties of labels.
type GetInfoResponse_LabelIndexDescription_PropertyDescription struct {
	// The name of the property.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A short description of the property.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// The data type of the property: str, float, or boolean; List[T] or Mapping[T1, T2] of those.
	DataType string `protobuf:"bytes,3,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	// Whether the property can have a valid value of null.
	Nullable             bool     `protobuf:"varint,4,opt,name=nullable,proto3" json:"nullable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoResponse_LabelIndexDescription_PropertyDescription) Reset() {
	*m = GetInfoResponse_LabelIndexDescription_PropertyDescription{}
}
func (m *GetInfoResponse_LabelIndexDescription_PropertyDescription) String() string {
	return proto.CompactTextString(m)
}
func (*GetInfoResponse_LabelIndexDescription_PropertyDescription) ProtoMessage() {}
func (*GetInfoResponse_LabelIndexDescription_PropertyDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_92219fa19b46411c, []int{4, 1, 0}
}

func (m *GetInfoResponse_LabelIndexDescription_PropertyDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoResponse_LabelIndexDescription_PropertyDescription.Unmarshal(m, b)
}
func (m *GetInfoResponse_LabelIndexDescription_PropertyDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoResponse_LabelIndexDescription_PropertyDescription.Marshal(b, m, deterministic)
}
func (m *GetInfoResponse_LabelIndexDescription_PropertyDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoResponse_LabelIndexDescription_PropertyDescription.Merge(m, src)
}
func (m *GetInfoResponse_LabelIndexDescription_PropertyDescription) XXX_Size() int {
	return xxx_messageInfo_GetInfoResponse_LabelIndexDescription_PropertyDescription.Size(m)
}
func (m *GetInfoResponse_LabelIndexDescription_PropertyDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoResponse_LabelIndexDescription_PropertyDescription.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoResponse_LabelIndexDescription_PropertyDescription proto.InternalMessageInfo

func (m *GetInfoResponse_LabelIndexDescription_PropertyDescription) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetInfoResponse_LabelIndexDescription_PropertyDescription) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetInfoResponse_LabelIndexDescription_PropertyDescription) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

func (m *GetInfoResponse_LabelIndexDescription_PropertyDescription) GetNullable() bool {
	if m != nil {
		return m.Nullable
	}
	return false
}

// A set of globally-aggregated measurements for a specific processor timer
// across all requests.
type TimerStats struct {
	// The mean duration.
	Mean *duration.Duration `protobuf:"bytes,1,opt,name=mean,proto3" json:"mean,omitempty"`
	// The standard deviation of the duration.
	Std *duration.Duration `protobuf:"bytes,2,opt,name=std,proto3" json:"std,omitempty"`
	// The maximum duration.
	Max *duration.Duration `protobuf:"bytes,3,opt,name=max,proto3" json:"max,omitempty"`
	// The minimum duration.
	Min *duration.Duration `protobuf:"bytes,4,opt,name=min,proto3" json:"min,omitempty"`
	// The sum of durations.
	Sum                  *duration.Duration `protobuf:"bytes,5,opt,name=sum,proto3" json:"sum,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TimerStats) Reset()         { *m = TimerStats{} }
func (m *TimerStats) String() string { return proto.CompactTextString(m) }
func (*TimerStats) ProtoMessage()    {}
func (*TimerStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_92219fa19b46411c, []int{5}
}

func (m *TimerStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimerStats.Unmarshal(m, b)
}
func (m *TimerStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimerStats.Marshal(b, m, deterministic)
}
func (m *TimerStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimerStats.Merge(m, src)
}
func (m *TimerStats) XXX_Size() int {
	return xxx_messageInfo_TimerStats.Size(m)
}
func (m *TimerStats) XXX_DiscardUnknown() {
	xxx_messageInfo_TimerStats.DiscardUnknown(m)
}

var xxx_messageInfo_TimerStats proto.InternalMessageInfo

func (m *TimerStats) GetMean() *duration.Duration {
	if m != nil {
		return m.Mean
	}
	return nil
}

func (m *TimerStats) GetStd() *duration.Duration {
	if m != nil {
		return m.Std
	}
	return nil
}

func (m *TimerStats) GetMax() *duration.Duration {
	if m != nil {
		return m.Max
	}
	return nil
}

func (m *TimerStats) GetMin() *duration.Duration {
	if m != nil {
		return m.Min
	}
	return nil
}

func (m *TimerStats) GetSum() *duration.Duration {
	if m != nil {
		return m.Sum
	}
	return nil
}

// Request for globally-aggregated statistics about the processor.
type GetStatsRequest struct {
	// The deployment identifier of the processor.
	ProcessorId          string   `protobuf:"bytes,1,opt,name=processor_id,json=processorId,proto3" json:"processor_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatsRequest) Reset()         { *m = GetStatsRequest{} }
func (m *GetStatsRequest) String() string { return proto.CompactTextString(m) }
func (*GetStatsRequest) ProtoMessage()    {}
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92219fa19b46411c, []int{6}
}

func (m *GetStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatsRequest.Unmarshal(m, b)
}
func (m *GetStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatsRequest.Marshal(b, m, deterministic)
}
func (m *GetStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatsRequest.Merge(m, src)
}
func (m *GetStatsRequest) XXX_Size() int {
	return xxx_messageInfo_GetStatsRequest.Size(m)
}
func (m *GetStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatsRequest proto.InternalMessageInfo

func (m *GetStatsRequest) GetProcessorId() string {
	if m != nil {
		return m.ProcessorId
	}
	return ""
}

// Processor statistics response.
type GetStatsResponse struct {
	// The number of documents processed.
	Processed int32 `protobuf:"varint,1,opt,name=processed,proto3" json:"processed,omitempty"`
	// The number of documents that have failed to process.
	Failures int32 `protobuf:"varint,2,opt,name=failures,proto3" json:"failures,omitempty"`
	// Statistics for each timer.
	TimingStats          map[string]*TimerStats `protobuf:"bytes,3,rep,name=timing_stats,json=timingStats,proto3" json:"timing_stats,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetStatsResponse) Reset()         { *m = GetStatsResponse{} }
func (m *GetStatsResponse) String() string { return proto.CompactTextString(m) }
func (*GetStatsResponse) ProtoMessage()    {}
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92219fa19b46411c, []int{7}
}

func (m *GetStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatsResponse.Unmarshal(m, b)
}
func (m *GetStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatsResponse.Marshal(b, m, deterministic)
}
func (m *GetStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatsResponse.Merge(m, src)
}
func (m *GetStatsResponse) XXX_Size() int {
	return xxx_messageInfo_GetStatsResponse.Size(m)
}
func (m *GetStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatsResponse proto.InternalMessageInfo

func (m *GetStatsResponse) GetProcessed() int32 {
	if m != nil {
		return m.Processed
	}
	return 0
}

func (m *GetStatsResponse) GetFailures() int32 {
	if m != nil {
		return m.Failures
	}
	return 0
}

func (m *GetStatsResponse) GetTimingStats() map[string]*TimerStats {
	if m != nil {
		return m.TimingStats
	}
	return nil
}

func init() {
	proto.RegisterType((*CreatedIndex)(nil), "mtap.api.v1.CreatedIndex")
	proto.RegisterType((*ProcessRequest)(nil), "mtap.api.v1.ProcessRequest")
	proto.RegisterType((*ProcessResponse)(nil), "mtap.api.v1.ProcessResponse")
	proto.RegisterMapType((map[string]*duration.Duration)(nil), "mtap.api.v1.ProcessResponse.TimingInfoEntry")
	proto.RegisterType((*GetInfoRequest)(nil), "mtap.api.v1.GetInfoRequest")
	proto.RegisterType((*GetInfoResponse)(nil), "mtap.api.v1.GetInfoResponse")
	proto.RegisterType((*GetInfoResponse_ParameterDescription)(nil), "mtap.api.v1.GetInfoResponse.ParameterDescription")
	proto.RegisterType((*GetInfoResponse_LabelIndexDescription)(nil), "mtap.api.v1.GetInfoResponse.LabelIndexDescription")
	proto.RegisterType((*GetInfoResponse_LabelIndexDescription_PropertyDescription)(nil), "mtap.api.v1.GetInfoResponse.LabelIndexDescription.PropertyDescription")
	proto.RegisterType((*TimerStats)(nil), "mtap.api.v1.TimerStats")
	proto.RegisterType((*GetStatsRequest)(nil), "mtap.api.v1.GetStatsRequest")
	proto.RegisterType((*GetStatsResponse)(nil), "mtap.api.v1.GetStatsResponse")
	proto.RegisterMapType((map[string]*TimerStats)(nil), "mtap.api.v1.GetStatsResponse.TimingStatsEntry")
}

func init() { proto.RegisterFile("mtap/api/v1/processing.proto", fileDescriptor_92219fa19b46411c) }

var fileDescriptor_92219fa19b46411c = []byte{
	// 964 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x51, 0x6f, 0x1b, 0x45,
	0x10, 0xd6, 0xd9, 0x71, 0x6c, 0x8f, 0x43, 0x12, 0xb6, 0xa0, 0x3a, 0x8e, 0x5b, 0xc2, 0x15, 0xa4,
	0xa8, 0xa5, 0x67, 0x92, 0x82, 0x84, 0xca, 0x5b, 0x29, 0x45, 0x41, 0x05, 0xa5, 0xd7, 0x48, 0xf0,
	0x66, 0x6d, 0x7c, 0x63, 0x6b, 0xc5, 0xdd, 0xee, 0x75, 0x77, 0x2f, 0x8a, 0x55, 0x55, 0x08, 0x04,
	0x12, 0xef, 0xfc, 0x05, 0xde, 0xf9, 0x31, 0xfc, 0x05, 0xde, 0x79, 0x84, 0x47, 0xb4, 0x7b, 0x7b,
	0x97, 0xf3, 0xc5, 0x38, 0x04, 0x89, 0xa7, 0x64, 0x66, 0xbe, 0xfd, 0xf6, 0x9b, 0x99, 0xbd, 0x19,
	0xc3, 0x30, 0xd1, 0x34, 0x1d, 0xd1, 0x94, 0x8d, 0xce, 0x0e, 0x46, 0xa9, 0x14, 0x13, 0x54, 0x8a,
	0xf1, 0x59, 0x90, 0x4a, 0xa1, 0x05, 0xe9, 0x99, 0x68, 0x40, 0x53, 0x16, 0x9c, 0x1d, 0x0c, 0x86,
	0x33, 0x21, 0x66, 0x31, 0x5a, 0x30, 0xe5, 0x5c, 0x68, 0xaa, 0x99, 0xe0, 0x2a, 0x87, 0x0e, 0x6e,
	0xbb, 0xa8, 0xb5, 0x4e, 0xb3, 0xe9, 0x28, 0xca, 0xa4, 0x05, 0xb8, 0xf8, 0xb0, 0x1e, 0x57, 0x5a,
	0x66, 0x13, 0x9d, 0x47, 0xfd, 0x10, 0x36, 0x3e, 0x91, 0x48, 0x35, 0x46, 0x47, 0x3c, 0xc2, 0x73,
	0x72, 0x07, 0x5e, 0x8b, 0xc4, 0x24, 0x4b, 0x90, 0xeb, 0x31, 0xa7, 0x09, 0xf6, 0xbd, 0x3d, 0x6f,
	0xbf, 0x1b, 0x6e, 0x14, 0xce, 0x2f, 0x69, 0x82, 0xe4, 0x16, 0x00, 0x33, 0xe8, 0x1c, 0xd1, 0xb0,
	0x88, 0xae, 0xf5, 0x98, 0xb0, 0xff, 0x2d, 0x6c, 0x1e, 0xe7, 0x09, 0x85, 0xf8, 0x22, 0x43, 0xa5,
	0xc9, 0xdb, 0xb0, 0xe1, 0x52, 0x14, 0x72, 0xcc, 0x22, 0x47, 0xda, 0x2b, 0x7d, 0x47, 0x11, 0xd9,
	0x81, 0x0e, 0x9e, 0x99, 0x5b, 0x59, 0xe4, 0x18, 0xdb, 0xd6, 0x3e, 0x8a, 0xc8, 0x08, 0xd6, 0x53,
	0x2a, 0x69, 0xa2, 0xfa, 0xcd, 0x3d, 0x6f, 0xbf, 0x77, 0x78, 0x33, 0xc8, 0x53, 0x0a, 0x8a, 0x94,
	0x82, 0xe7, 0x36, 0xa5, 0xd0, 0xc1, 0xfc, 0x5f, 0x1b, 0xb0, 0x55, 0x2a, 0x50, 0xa9, 0xe0, 0x0a,
	0xc9, 0x17, 0xd0, 0xd3, 0x2c, 0x61, 0x7c, 0x36, 0x66, 0x7c, 0x2a, 0xfa, 0xde, 0x5e, 0x73, 0xbf,
	0x77, 0xf8, 0x5e, 0x50, 0xa9, 0x73, 0x50, 0x3b, 0x12, 0x9c, 0x58, 0xfc, 0x11, 0x9f, 0x8a, 0x4f,
	0xb9, 0x96, 0xf3, 0x10, 0x74, 0xe9, 0x30, 0x9a, 0x24, 0xaa, 0x2c, 0xd6, 0x56, 0xec, 0x2a, 0x4d,
	0x39, 0x8c, 0x3c, 0x82, 0xad, 0x49, 0x5e, 0xe8, 0x31, 0xe3, 0x11, 0x9b, 0xa0, 0xc9, 0xc6, 0x68,
	0xd8, 0x59, 0xd0, 0x50, 0x6d, 0x46, 0xb8, 0x39, 0x29, 0x2d, 0x73, 0x60, 0xf0, 0x35, 0x6c, 0xd5,
	0x34, 0x91, 0x6d, 0x68, 0x7e, 0x83, 0x73, 0x57, 0x50, 0xf3, 0x2f, 0x19, 0x41, 0xeb, 0x8c, 0xc6,
	0x19, 0x3a, 0x61, 0x3b, 0x97, 0x84, 0x3d, 0x76, 0xef, 0x23, 0xcc, 0x71, 0x0f, 0x1b, 0x1f, 0x79,
	0xfe, 0x03, 0xd8, 0xfc, 0x0c, 0xb5, 0xa1, 0xfd, 0xf7, 0x2d, 0xf3, 0x7f, 0x69, 0xc3, 0x56, 0x79,
	0xca, 0x95, 0x99, 0xc0, 0x5a, 0xe5, 0xd9, 0xd8, 0xff, 0xc9, 0x6d, 0x00, 0x16, 0x21, 0xd7, 0x6c,
	0xca, 0x50, 0xba, 0xe6, 0x56, 0x3c, 0x64, 0x0f, 0x7a, 0x11, 0xaa, 0x89, 0x64, 0xa9, 0x91, 0x65,
	0x9b, 0xdc, 0x0d, 0xab, 0x2e, 0xf2, 0x16, 0xf4, 0xd0, 0xa4, 0x3b, 0x4e, 0x05, 0xe3, 0xba, 0xbf,
	0x96, 0x53, 0x58, 0xd7, 0xb1, 0xf1, 0x90, 0x01, 0x74, 0x62, 0xca, 0x67, 0x19, 0x9d, 0x61, 0xbf,
	0x65, 0xa3, 0xa5, 0x4d, 0x9e, 0x01, 0xd8, 0x77, 0x81, 0x1a, 0xa5, 0xea, 0xaf, 0xdb, 0xa2, 0x1f,
	0x2c, 0x14, 0xbd, 0x96, 0x44, 0x70, 0x5c, 0xc0, 0x1f, 0x5f, 0x68, 0x08, 0x2b, 0x24, 0xe4, 0x73,
	0x58, 0x67, 0x3c, 0xcd, 0xb4, 0xea, 0xb7, 0x2d, 0xdd, 0xe1, 0x4a, 0xba, 0xa7, 0xf4, 0x14, 0x63,
	0xdb, 0xd1, 0x2a, 0x9f, 0x63, 0x20, 0x4f, 0xa1, 0x2d, 0x32, 0x6d, 0xc9, 0x3a, 0xff, 0x99, 0xac,
	0xa0, 0x18, 0xfc, 0xe8, 0xc1, 0x1b, 0xcb, 0xe4, 0x2f, 0x6d, 0x4c, 0xad, 0xf0, 0x8d, 0xcb, 0x85,
	0xdf, 0x85, 0x6e, 0x44, 0x35, 0x1d, 0xeb, 0x79, 0x8a, 0xae, 0x31, 0x1d, 0xe3, 0x38, 0x99, 0xa7,
	0x68, 0x8a, 0x2e, 0xf1, 0x45, 0xc6, 0x24, 0x46, 0xb6, 0x25, 0x9d, 0xb0, 0xb4, 0x07, 0x3f, 0x35,
	0xe1, 0xcd, 0xa5, 0x52, 0x97, 0x0a, 0x09, 0xe0, 0x86, 0xf9, 0x3b, 0x9e, 0x4a, 0x91, 0x8c, 0xcb,
	0x3a, 0x3b, 0x41, 0xaf, 0x9b, 0xd0, 0x13, 0x29, 0x92, 0x32, 0x2f, 0x73, 0xb3, 0xb0, 0x6c, 0x34,
	0xb6, 0xaa, 0x3a, 0x61, 0x69, 0xd7, 0x93, 0x5a, 0xbb, 0x9c, 0xd4, 0x14, 0x20, 0x95, 0x22, 0x45,
	0xa9, 0x19, 0xaa, 0x7e, 0xcb, 0x16, 0xfd, 0xc9, 0xf5, 0x8b, 0x6e, 0xe6, 0x85, 0x21, 0x99, 0x2f,
	0xbe, 0x92, 0x92, 0x79, 0xf0, 0x83, 0x07, 0x37, 0x96, 0x60, 0xfe, 0xa7, 0x56, 0xf0, 0x2c, 0x8e,
	0xe9, 0x69, 0x8c, 0x45, 0x2b, 0x0a, 0xdb, 0xff, 0xc3, 0x03, 0x38, 0x61, 0x09, 0xca, 0xe7, 0x9a,
	0x6a, 0x45, 0xee, 0xc3, 0x5a, 0x82, 0x94, 0xdb, 0xdb, 0x57, 0x8e, 0x07, 0x0b, 0x23, 0xf7, 0xa0,
	0xa9, 0x74, 0x74, 0xf5, 0x30, 0x31, 0x28, 0x03, 0x4e, 0xe8, 0xb9, 0x1b, 0xd3, 0xab, 0xc0, 0x09,
	0x3d, 0xb7, 0x60, 0x96, 0x37, 0xe8, 0x0a, 0x30, 0xcb, 0x65, 0x64, 0x89, 0xfd, 0xb6, 0xaf, 0x90,
	0x91, 0x25, 0xfe, 0x07, 0x76, 0x2e, 0xd9, 0x74, 0xaf, 0x31, 0xce, 0xfe, 0xf2, 0x60, 0xfb, 0xe2,
	0x98, 0x9b, 0x67, 0x43, 0xe8, 0x3a, 0x0c, 0xe6, 0x87, 0x5a, 0xe1, 0x85, 0xc3, 0x94, 0x7d, 0x4a,
	0x59, 0x9c, 0x49, 0x54, 0xb6, 0x42, 0xad, 0xb0, 0xb4, 0xc9, 0x33, 0xd8, 0x70, 0x0b, 0x47, 0x19,
	0x46, 0x37, 0xed, 0x83, 0xfa, 0x3b, 0x5b, 0xb8, 0xce, 0xad, 0x1c, 0xeb, 0xcb, 0x77, 0x8e, 0x5b,
	0x5a, 0xd6, 0x33, 0xf8, 0x0a, 0xb6, 0xeb, 0x80, 0x25, 0x0b, 0xe0, 0xfe, 0xe2, 0x02, 0xb8, 0xb9,
	0x70, 0xe3, 0xc5, 0x43, 0xa8, 0x8c, 0xff, 0xc3, 0x3f, 0x1b, 0xd0, 0x3d, 0x2e, 0x4a, 0x41, 0xbe,
	0xf3, 0xa0, 0xed, 0x2c, 0xb2, 0xbb, 0x7c, 0x43, 0xda, 0xa2, 0x0e, 0x86, 0xab, 0xd6, 0xa7, 0xff,
	0xf1, 0xf7, 0xbf, 0xfd, 0xfe, 0x73, 0xe3, 0x43, 0xff, 0xfd, 0xca, 0x2f, 0x1c, 0x21, 0xd5, 0xe8,
	0x65, 0xb5, 0x11, 0xaf, 0x8a, 0xc8, 0xe8, 0x65, 0xb1, 0xfe, 0x5f, 0x3d, 0xf4, 0xee, 0x92, 0x14,
	0xda, 0xee, 0x23, 0xac, 0x49, 0x58, 0x5c, 0x53, 0x35, 0x09, 0xb5, 0xef, 0xd6, 0xbf, 0x6b, 0x25,
	0xbc, 0x43, 0xfc, 0xd5, 0x12, 0xcc, 0x2f, 0x02, 0xa2, 0xa1, 0x53, 0xb4, 0x83, 0x0c, 0xff, 0xa1,
	0x4b, 0xf9, 0x9d, 0xb7, 0x56, 0xf6, 0xd0, 0xbf, 0x67, 0x2f, 0x7d, 0x97, 0xdc, 0x59, 0x7d, 0xa9,
	0x7d, 0x15, 0x8f, 0x76, 0x61, 0x07, 0xa3, 0x2c, 0xc8, 0x12, 0x1e, 0xf0, 0x38, 0x65, 0x58, 0xa5,
	0x3e, 0x5d, 0xb7, 0xef, 0xfb, 0xc1, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x1c, 0x72, 0xbc,
	0x2c, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProcessorClient is the client API for Processor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProcessorClient interface {
	// Processes an event.
	Process(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResponse, error)
	// Gets information about the processor.
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
	// Gets globally-aggregated statistics about the processor.
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
}

type processorClient struct {
	cc *grpc.ClientConn
}

func NewProcessorClient(cc *grpc.ClientConn) ProcessorClient {
	return &processorClient{cc}
}

func (c *processorClient) Process(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResponse, error) {
	out := new(ProcessResponse)
	err := c.cc.Invoke(ctx, "/mtap.api.v1.Processor/Process", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processorClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, "/mtap.api.v1.Processor/GetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processorClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, "/mtap.api.v1.Processor/GetStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProcessorServer is the server API for Processor service.
type ProcessorServer interface {
	// Processes an event.
	Process(context.Context, *ProcessRequest) (*ProcessResponse, error)
	// Gets information about the processor.
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	// Gets globally-aggregated statistics about the processor.
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
}

// UnimplementedProcessorServer can be embedded to have forward compatible implementations.
type UnimplementedProcessorServer struct {
}

func (*UnimplementedProcessorServer) Process(ctx context.Context, req *ProcessRequest) (*ProcessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Process not implemented")
}
func (*UnimplementedProcessorServer) GetInfo(ctx context.Context, req *GetInfoRequest) (*GetInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (*UnimplementedProcessorServer) GetStats(ctx context.Context, req *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}

func RegisterProcessorServer(s *grpc.Server, srv ProcessorServer) {
	s.RegisterService(&_Processor_serviceDesc, srv)
}

func _Processor_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessorServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtap.api.v1.Processor/Process",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessorServer).Process(ctx, req.(*ProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Processor_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessorServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtap.api.v1.Processor/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessorServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Processor_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessorServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtap.api.v1.Processor/GetStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessorServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Processor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mtap.api.v1.Processor",
	HandlerType: (*ProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _Processor_Process_Handler,
		},
		{
			MethodName: "GetInfo",
			Handler:    _Processor_GetInfo_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _Processor_GetStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mtap/api/v1/processing.proto",
}
